version: "3.9"
   
services:

  datascience-notebook:
      image: jupyter/datascience-notebook
      volumes:
        - .:/home/jovyan/work
      ports:
        - 8888:8888
      container_name: ds-notebook-container
      links:
        - postgres

  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
 